// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Greeter.proto

package com.cooba.proto;

public interface HelloReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:proto.HelloReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string message = 1;</code>
   * @return The message.
   */
  String getMessage();
  /**
   * <code>string message = 1;</code>
   * @return The bytes for message.
   */
  com.google.protobuf.ByteString
      getMessageBytes();
}
